### ISSUE TITLE
HELLO~Excuse me 

### ISSUE THREAD

**Issue by giorno63** [bmoren/node-omxplayer-sync#4]
Does the film support for more than 10 minutes up? 
I tried a video that was longer than 10 minutes and could not be synced.
thank you~

**Comment by DSPeelJ** [comment]
I haven't used this implementation of omxplayer-sync so I can't answer your question.  I have had good success with the TuringMachine one though.  https://github.com/turingmachine/omxplayer-sync  I have multiple 15 minute videos working on it.

**Comment by bmoren** [comment]
Have you been able to sync with shorter videos? 
It should work with anything that the native OMX player supports. it's worth noting that this project works differently from the turingmachine project. One major difference is that the turing machine project needs a special version of omx player, whereas this uses the default distribution. It's also written in python and this is in JS with node.

try a short video, around 1 minute to get all of the networking issues sorted out, and them move onto a longer video once you've confirmed there are no other issues in the system.
