### ISSUE TITLE
forever keeps restarting all the time

### ISSUE THREAD

**Issue by elalemanyo** [bmoren/node-omxplayer-sync#6]
Hi,
When I try to run the script with forever the video is restarting all the time without running not even once.
What I see in the logs is:
```
Listener connected: q4Kw79RJb1PWDmvEAAAA @ Sat Feb 01 2020 19:17:20 GMT+0000 (UTC)
Duration: undefined
EXIT CODE: 143 @ Sat Feb 01 2020 19:17:22 GMT+0000 (UTC)
error: Forever detected script exited with code: 0
error: Script restart attempt #15
```

When I run without forever everything works...

Thanks for the repo!

**Comment by bmoren** [comment]
Are you sshing into the pi while playing back the video?
if so can you run `forever list`
My guess is that you've got 2 copies of the script running, one that started when the pi booted, and a second that started when you sshed in. 
you can use `forever stop` to stop one of the instances.

**Comment by elalemanyo** [comment]
I think your guess was correct, if I don't ssh into the pi everything works great.
Thanks!
